// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkzdavyypnmitjzogyqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1remRhdnl5cG5taXRqem9neXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5Mzk3NjIsImV4cCI6MjA0OTUxNTc2Mn0.NDrEZ5JbUv2-eia7f-yZeOCktf4AVLWepDa6Ladmzeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);